"""Add EventEnrollment Model

Revision ID: 1150136bf0ab
Revises: 8ca4a81f067e
Create Date: 2016-06-21 21:48:19.804906

"""

# revision identifiers, used by Alembic.
revision = '1150136bf0ab'
down_revision = '8ca4a81f067e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_enrollments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_enrollments')
    ### end Alembic commands ###
