"""Create tables

Revision ID: 8ca4a81f067e
Revises: None
Create Date: 2016-06-17 15:04:19.408344

"""

# revision identifiers, used by Alembic.
revision = '8ca4a81f067e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
    )

    op.create_table('auth_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
    )

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('pw_hash', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column('gender', sa.Boolean(), nullable=False),
        sa.Column('birth_date', sa.Date(), nullable=False),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    op.create_table('event_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('points', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('time', sa.Time(), nullable=False),
        sa.Column('image_path', sa.String(length=255), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('publisher_id', sa.Integer(), nullable=False),
        sa.Column('published_on', sa.DateTime(), nullable=False),

        sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ),
        sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('role_permission_rel',
        sa.Column('role', sa.Integer(), nullable=True),
        sa.Column('permission', sa.Integer(), nullable=True),

        sa.ForeignKeyConstraint(['permission'], ['auth_permissions.id'], ),
        sa.ForeignKeyConstraint(['role'], ['auth_roles.id'], )
    )

    op.create_table('user_role_rel',
        sa.Column('user', sa.Integer(), nullable=True),
        sa.Column('role', sa.Integer(), nullable=True),

        sa.ForeignKeyConstraint(['role'], ['auth_roles.id'], ),
        sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )

    op.create_table('user_event_rel',
        sa.Column('user', sa.Integer(), nullable=True),
        sa.Column('event', sa.Integer(), nullable=True),

        sa.ForeignKeyConstraint(['event'], ['events.id'], ),
        sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event_rel')
    op.drop_table('user_role_rel')
    op.drop_table('role_permission_rel')
    op.drop_table('events')
    op.drop_table('event_categories')
    op.drop_table('users')
    op.drop_table('auth_roles')
    op.drop_table('auth_permissions')
    ### end Alembic commands ###
