"""Add columns to Event model
Columns added:
    location_name
    latitude
    longitude
    price
    and max_attendants

Revision ID: f90d3b386518
Revises: 1150136bf0ab
Create Date: 2016-08-08 11:30:45.154593

"""

# revision identifiers, used by Alembic.
revision = 'f90d3b386518'
down_revision = '1150136bf0ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('events', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('max_attendants', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'price')
    op.drop_column('events', 'max_attendants')
    op.drop_column('events', 'location_name')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    ### end Alembic commands ###
